name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # 触发分支（根据你的实际分支名调整）

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy public/ to root
        run: |
          # 删除根目录下所有文件（除了 .git/ 和 public/）
          find . -maxdepth 1 ! -name '.' ! -name '.git' ! -name 'public' -exec rm -rf {} +
          # 将 public/ 下的所有内容移动到根目录
          cp -r public/* .
          # 可选：删除空的 public/ 文件夹（如果不需要保留）
          rm -rf public/

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy: Copy public/ to root" || echo "No changes to commit"
          git push