name: Update News Daily

on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间中午12点运行（多伦多时间早8点）
  workflow_dispatch:      # 允许手动触发

jobs:
  generate-news:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Fetch News
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: |
        mkdir -p public
        curl -s "https://newsapi.org/v2/top-headlines?country=ca&category=technology&pageSize=5&apiKey=${NEWS_API_KEY}" \
        | jq '[.articles[] | {title, description, url, publishedAt}]' \
        > public/news.json

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add public/news.json
        git commit -m "Auto-update news data"
        git push
